# Generated by Django 6.0.8 on 2026-08-05 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('applied_date', models.DateField()),
                ('status', models.CharField(choices=[('Wishlist', 'Wishlist'), ('Applied', 'Applied'), ('Interview Scheduled', 'Interview Scheduled'), ('Interviewing', 'Interviewing'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Joined', 'Joined'), ('Withdrawn', 'Withdrawn')], default='Applied', max_length=50)),
                ('salary', models.CharField(blank=True, default='', max_length=100)),
                ('platform', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Indeed', 'Indeed'), ('Naukri', 'Naukri'), ('Glassdoor', 'Glassdoor'), ('Company Website', 'Company Website'), ('Referral', 'Referral'), ('Other', 'Other')], default='LinkedIn', max_length=100)),
                ('job_url', models.URLField(blank=True, default='', max_length=500)),
                ('recruiter_name', models.CharField(blank=True, default='', max_length=255)),
                ('recruiter_email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='application_user_id_55b4e4_idx'), models.Index(fields=['user', 'applied_date'], name='application_user_id_48243f_idx')],
            },
        ),
    ]
