# Generated by Django 6.0.8 on 2026-08-13 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_gmailcredential_application_gmail_message_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255)),
                ('gmail_thread_id', models.CharField(blank=True, default='', max_length=255)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True, default='')),
                ('snippet', models.TextField(blank=True, default='')),
                ('is_job_related', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], default='PENDING', max_length=50)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GmailConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_uri', models.CharField(default='https://oauth2.googleapis.com/token', max_length=255)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('scopes', models.TextField(blank=True, default='https://www.googleapis.com/auth/gmail.readonly')),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('last_history_id', models.CharField(blank=True, default='', max_length=100)),
                ('watch_expiration', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gmailcredential',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='gmail_thread_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='source_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'gmail_thread_id'], name='application_user_id_0b045c_idx'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.application'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_events', to='applications.emailmessage'),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_connection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GmailCredential',
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['user', 'received_at'], name='application_user_id_70e916_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['user', 'processing_status'], name='application_user_id_0b0908_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['user', 'is_job_related'], name='application_user_id_8a46f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailmessage',
            constraint=models.UniqueConstraint(fields=('user', 'gmail_message_id'), name='unique_user_gmail_message'),
        ),
    ]
