# Generated by Django 6.0.8 on 2026-08-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationevent_emailmessage_gmailconnection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='extracted_company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='extracted_job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='extracted_platform',
            field=models.CharField(blank=True, default='LinkedIn', max_length=100),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='extracted_recruiter_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='extracted_recruiter_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='extracted_status',
            field=models.CharField(blank=True, default='Applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_REVIEW', 'Pending Review'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], default='PENDING', max_length=50),
        ),
    ]
