# Generated by Django 6.0.8 on 2026-08-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_emailmessage_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailconnection',
            name='sync_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='sync_status',
            field=models.CharField(default='IDLE', max_length=50),
        ),
    ]
