# Generated by Django 6.0.8 on 2026-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_gmailconnection_sync_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='ai_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='extraction_source',
            field=models.CharField(default='REGEX_PARSER', max_length=50),
        ),
    ]
