version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: job_tracker_db
    restart: always
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: job_tracker_backend
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-docker-secret-key
      - DEBUG=True
      - DB_NAME=jobtracker
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
